### ISSUE TITLE
Does dotNetify work with Blazor Server or is it WebAssembly Only

### ISSUE THREAD

**Issue by JeremyGEA** [dsuryd/dotNetify-Blazor#2]
I know your page says WebAssembly but I was wondering if this is the case, why will it only work for WebAssembly?

**Comment by dsuryd** [comment]
DotNetify's intent is to facilitate and abstract real-time communication with SignalR between the code that runs in the client browser and the server.  It doesn't fit Blazor Server because Blazor Server's code runs on the server and employs its own SignalR abstraction to send/receive UI updates.

**Comment by JeremyGEA** [comment]
Okay, thanks for the explanation.
