### ISSUE TITLE
VMArg keys forced to camel case

### ISSUE THREAD

**Issue by smfields** [dsuryd/dotNetify-Blazor#7]
I'm trying to initialize my VM using the VMContext => Options => VMArg dictionary, however when the dictionary is serialized and sent to the server all the key values are set to lowercase. This means they aren't being detected properly on the server, and the values aren't being initialized.

VMConnectOptions:
```csharp
  private readonly VMConnectOptions _connectOptions = new()
  {
      VMArg = new Dictionary<string, object>
      {
          {
              "GameId", Guid.NewGuid()
          },
          {
              "Players", new List<PlayerDto>()
          }
      }
  };
```

Message sent over websocket:
```json
{"arguments":["HostGameViewModel",{"$vmArg":{"gameId":"279ec191-0dc1-4a0d-9d8b-01fb849b5618","players":[]},"$headers":null}],"invocationId":"0","target":"Request_VM","type":1}
```

The default `CamelCasePropertyNamesContractResolver` you use when serializing the `VMConnectOptions` uses `ProcessDictionaryKeys = true`. Setting this to `false` would resolve this issue. I can open a PR with this change to show you what I mean.

**Comment by smfields** [comment]
Hey @dsuryd, are you planning to publish a new Nuget package with these changes?

**Comment by dsuryd** [comment]
This is published.
